import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SideBar, NavBar } from "../_components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Playlist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ overflowY: "hidden" }}>
        <div className="p-4  flex h-screen">
          <SideBar />
          <div className="flex flex-col flex-1">
            <NavBar />
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
