import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "./toast-provider";
import ReduxProvider from "./redux-store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Playlist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <ToastProvider>
          <body className={inter.className}>
            <div>{children}</div>
          </body>
        </ToastProvider>
      </ReduxProvider>
    </html>
  );
}
