name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        env:
          SSH_KEY: ${{ secrets.IONOS_SSH_KEY }}
          USERNAME: ${{ secrets.IONOS_USERNAME }}
          HOST: ${{ secrets.IONOS_HOST }}
        run: |
          echo "${SSH_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          rsync -avz -e "ssh -i /tmp/ssh_key" ./ root@212.227.237.168:/var/www/html/ThePlaylist
