name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create ~/.ssh directory if not exists
        run: mkdir -p ~/.ssh

      - name: Set permissions for ~/.ssh directory
        run: chmod 700 ~/.ssh

      - name: Print SSH Key
        run: echo SSH Key: ${{ secrets.IONOS_SSH_KEY }}

      - name: Print Host
        run: echo SSH Key: ${{ secrets.IONOS_HOST }}

      - name: Ensure known_hosts file exists
        run: touch ~/.ssh/known_hosts

      - name: Add host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.IONOS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        env:
          SSH_KEY: ${{ secrets.IONOS_SSH_KEY }}
          USERNAME: ${{ secrets.IONOS_USERNAME }} # or 'root' if hardcoded
          HOST: ${{ secrets.IONOS_HOST }} # or '212.227.237.168' if hardcoded
        run: |
          echo "${SSH_KEY}" > /tmp/ssh_key
          chmod 600 /tmp/ssh_key
          rsync -avz -e "ssh -i /tmp/ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -vvv" ./ root@212.227.237.168:/var/www/html/ThePlaylist
